laravel_lms_/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/author', function () {
    return view('author');
});


Route::resource('/author','AuthorController');
Route::resource('/book','BookController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/active-deactive','AuthorController@Confirm');
Route::post('/active-deactive1','BookController@Confirm_');
//Route::get('/updateBookStatus/{id}','BookController@updateBookStatus');

laravel_lms_/resources/views/author.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                            <button class="btn btn-primary mx-auto"><a href="{{ route('author.create') }}" class="text-white">Fill Author Data</a></button>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-dark">
                            <thead>
                            <tr>
                                <th scope="col">FullName</th>
                                <th scope="col">Dob</th>
                                <th scope="col">Gender</th>
                                <th scope="col">Address</th>
                                <th scope="col">Mobile_no</th>
                                <th scope="col">Description</th>
                                <th scope="col">Status</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Updated At</th>
                                <th scope="col"><Activity></Activity></th>
                            </tr>
                            </thead>
                            <tbody>
                        @foreach($author as $as)
                            <tr>
                                <th scope="row">{{$as->fullname}}</th>
                                <td>{{$as->dob}}</td>
                                <td>{{$as->gender}}</td>
                                <td>{{$as->address_ }}</td>
                                <td>{{$as->mobile_no}}</td>
                                <td>{{$as->description_}}</td>
                                <td>{{$as->status}}</td>
                                <td>{{$as->created_at}}</td>
                                <td>{{$as->updated_at}}</td>
                                <td><a class="btn btn-primary" href="{{ route('author.edit',$as->id) }}">Edit</a></td>
                                <td>
                                <form action="{{ route('author.destroy',$as->id) }}" method="POST">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger">Delete</button>
                                </form>

                                 </td>
                                    <td><button class="btn btn-info "><a href="{{route('author.show',$as->id)}}">Show</a></button></td>
                                    <td>

                                        <form action="/active-deactive" method="POST">
                                            @csrf
                                            <div class="input-group">
                                                <input type="hidden" class="form-control" name="v" value="{{$as->id}}">
                                                <select required class="form-control" id="status"  name="status">
                                                    <option value="1">Active</option>
                                                    <option value="0">De-Active</option>
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-primary">
                                                <span>Confirm</span>
                                            </button>

                    </form>

                                    </td>
                            </tr>
                        @endforeach

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel_lms_/resources/views/authorcreate.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('author.store') }}" method="POST" id="myform" name="form">
                @csrf
            <div class="form-group">
                <label for="exampleInputEmail1">Full Name</label>
                <input type="text" name="fullname" id="firstname" class="form-control aa" id="firstname" aria-describedby="emailHelp" placeholder="Enter First Name">
                <span class="text-danger">  @error('fullname')
                        {{$message}}
                 @enderror
                </span>
            </div>



            <div class="form-group">
                <label for="exampleInputPassword1">Date-of-Birth</label>
                <input type="date" class="form-control" name="dob" id="dob" placeholder="Date-of-Birth">
                <span class="text-danger">  @error('dob')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1"  class="pr-5">Select Your Gender</label>
                <input type="radio" name="gender" checked="checked" value="male"> Male
                <input type="radio" name="gender" value="female"> Female
                <input type="radio" name="gender" value="other"> Other
                <span class="text-danger">  @error('gender')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Address</label><br>
                <input type="text" class="form-control" id="desc1" name="address_" placeholder="Enter your Address">
                <span class="text-danger">  @error('address_')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Mobile No</label>
                <input type="number" class="form-control" id="m_number" name="mobile_no" placeholder="Enter Mobile Number">
                <span class="text-danger">  @error('mobile_no')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Description</label><br>
                <textarea rows="4" cols="50" id="desc" name="description_">
                            data is not avalable
                    </textarea>
            </div>

            <button type="submit" class="btn btn-primary" name="submit" id="submit">Submit</button>

        </form>
    </div>
@endsection

laravel_lms_/resources/views/authoredit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <form action="{{ route('author.update',$author->id) }}" method="POST" id="myform" name="form">

            @method('PUT')
            @csrf

            <div class="form-group">
                <label for="exampleInputEmail1">Full Name</label>
                <input type="text" name="fullname" id="firstname" value="{{$author->fullname}}"  class="form-control aa" id="firstname" aria-describedby="emailHelp" placeholder="Enter First Name">
                <span class="text-danger">  @error('fullname')
                    {{$message}}
                    @enderror
                </span>
            </div>



            <div class="form-group">
                <label for="exampleInputPassword1">Date-of-Birth</label>
                <input type="date" class="form-control" name="dob" value="{{$author->dob}}" id="dob" placeholder="Date-of-Birth">
                <span class="text-danger">  @error('dob')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1"   class="pr-5">Select Your Gender</label>
                <input type="radio" name="gender"  checked="checked" value="male"> Male
                <input type="radio" name="gender"  value="female"> Female
                <input type="radio" name="gender" value="other"> Other
                <span class="text-danger">  @error('gender')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Address</label><br>
                <input type="text" class="form-control" id="desc1" name="address_"  value="{{$author->address_}}"placeholder="Enter your Address">
                <span class="text-danger">  @error('address_')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Mobile No</label>
                <input type="number" class="form-control" id="m_number" name="mobile_no"  value="{{$author->mobile_no}}" placeholder="Enter Mobile Number">
                <span class="text-danger">  @error('mobile_no')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Description</label><br>
                <textarea rows="4" cols="50" id="desc" name="description_">
                            {{$author->description_}}
                    </textarea>
            </div>

            <button type="submit" class="btn btn-primary" name="submit" id="submit">Submit</button>

        </form>
    </div>
@endsection

laravel_lms_/resources/views/book.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <button class="btn btn-primary mx-auto"><a href="{{ route('book.create') }}" class="text-white">Fill book Data</a></button>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-dark">
                            <thead>
                            <tr>
                                <th scope="col">author_id</th>
                                <th scope="col">title</th>
                                <th scope="col">pages</th>
                                <th scope="col">langauge</th>
                                <th scope="col">Cover_image</th>
                                <th scope="col">isbn</th>
                                <th scope="col">description</th>
                                <th scope="col">Status</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Updated At</th>
                                <th scope="col">Activity</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($book as $bk)
                                <tr>
                                    <th scope="row">{{$bk->author_id}}</th>
                                    <th scope="row">{{$bk->title}}</th>
                                    <td>{{$bk->pages}}</td>
                                    <td>{{$bk->langauge}}</td>
                                    <td>{{$bk->cover_image }}</td>
                                    <td>{{$bk->isbn}}</td>
                                    <td>{{$bk->description}}</td>
                                    <td>{{$bk->status}}</td>
                                    <td>{{$bk->created_at}}</td>
                                    <td>{{$bk->updated_at}}</td>
                                    <td><a class="btn btn-primary" href="{{ route('book.edit',$bk->id) }}">Edit</a></td>
                                    <td>
                                        <form action="{{ route('book.destroy',$bk->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>

                                    </td>
                                    <td><button class="btn btn-info "><a href="{{route('book.show',$bk->id)}}">Show</a></button></td>

                                    <td>

                                        <form action="/active-deactive1" method="POST">
                                            @csrf
                                            <div class="input-group">
                                                <input type="hidden" class="form-control" name="v" value="{{$bk->id}}">
                                                <select required class="form-control" id="status"  name="status">
                                                    <option value="1">Active</option>
                                                    <option value="0">De-Active</option>
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-primary">
                                                <span>Confirm</span>
                                            </button>

                                        </form>

{{--                                        @if($book->status==1)--}}
{{--                                            <a href="{{ route('statusBook',[$book->id]) }}" class="btn btn-danger">Inactive</a>--}}
{{--                                        @else--}}
{{--                                            <a href="{{ route('statusBook',[$book->id]) }}" class="btn btn-warning">active</a>--}}
{{--                                        @endif--}}


                                    </td>


                                </tr>
                            @endforeach

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel_lms_/resources/views/bookcreate.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">



        <form action="{{ route('book.store') }}" method="POST" id="myform" name="form" enctype="multipart/form-data">
            @csrf

            <div class="form-group">
                <label for="">Book Author</label>
                <select class="custom-select @error('book_author') is-invalid @enderror" name="author_id" id="author_id">
                    <option hidden value="">Book Author</option>
                    @foreach($author as $author)
                        <option value="{{ $author->id }}">{{ $author->fullname}}</option>
                    @endforeach
                </select>
                <span class="text-danger">
                @error('author_id')
                {{$message}}
                @enderror
                </span>
            </div>


            <div class="form-group">
            <label for="exampleInputEmail1">Title</label>
            <input type="text" name="title" id="title" class="form-control" aria-describedby="emailHelp" placeholder="Enter Book Title">
                <span class="text-danger">
                @error('title')
                    {{$message}}
                    @enderror
                </span>

            </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Pages</label>
            <input type="number" name="pages" id="pages" class="form-control" id="lastname" aria-describedby="emailHelp" placeholder="Enter Pages">

            <span class="text-danger">
                @error('pages')
                {{$message}}
                @enderror
                </span>
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">langauge</label>
            <input type="text" class="form-control" name="langauge" id="langauge" placeholder="Enter Book Langauge">

            <span class="text-danger">
                @error('langauge')
                {{$message}}
                @enderror
                </span>
        </div>







        <div class="form-group">
            <label for="exampleInputPassword1">Cover Image</label>
            <input type="file" class="form-control" id="image" name="cover_image" placeholder="Enter Cover Image">

            <span class="text-danger">
                @error('cover_image')
                {{$message}}
                @enderror
                </span>
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">ISBN Number</label>
            <input type="text" class="form-control" name="isbn" id="isbn" placeholder="Isbn Number">
            <span class="text-danger">
                @error('isbn')
                {{$message}}
                @enderror
                </span>
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">Description</label><br>
            <textarea rows="4" cols="50" id="desc" name="description" placeholder="Description">
    </textarea>
            <span class="text-danger">
                @error('description')
                {{$message}}
                @enderror
                </span>
        </div>

        <button type="submit" class="btn btn-primary" name="submit" id="submit">Submit</button>

    </form>
    </div>
@endsection

laravel_lms_/resources/views/bookedit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <form action="{{ route('book.update',$book->id) }}" method="POST" id="myform" name="form">

            @method('PUT')
            @csrf

            <div class="form-group">
                <label for="exampleInputEmail1">Title</label>
                <input type="text" name="title" id="title" class="form-control" aria-describedby="emailHelp" value={{$book->title}} placeholder="Enter Book Title">
                <span class="text-danger">  @error('title')
                    {{$message}}
                    @enderror
                </span>
            </div>



            <div class="form-group">
                <label for="exampleInputEmail1">Pages</label>
                <input type="number" name="pages" id="pages" class="form-control" id="lastname" aria-describedby="emailHelp"  value={{$book->pages}} placeholder="Enter Pages">
                <span class="text-danger">  @error('pages')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">langauge</label>
                <input type="text" class="form-control" name="langauge" value={{$book->langauge}} id="langauge" placeholder="Enter Book Langauge">
               <span class="text-danger">
                @error('langauge')
                    {{$message}}
                    @enderror
                </span>
            </div>

{{--            <div class="form-group">--}}
{{--                <label for="">Book Author</label>--}}
{{--                <select class="" name="author" id="author">--}}
{{--                </select>--}}
{{--            </div>--}}

            <div class="form-group">
                <label for="">Book Author</label>
                <select class="custom-select @error('book_author') is-invalid @enderror"  name="author_id" id="author_id">
                    <option hidden value={{$book->author_id}}>{{$book->author_id}}  </option>
                    @foreach($author as $author)
                        <option value="{{ $author->id }}">{{ $author->fullname}}</option>
                    @endforeach
                </select>
                <span class="text-danger">
                @error('author_id')
                    {{$message}}
                    @enderror
                </span>
            </div>



            <div class="form-group">
                <label for="exampleInputPassword1">Cover Image</label>
                <input type="file" class="form-control" id="image" name="image" value={{$book->cover_image}} placeholder="Enter Cover Image">
                <span class="text-danger">  @error('image')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">ISBN Number</label>
                <input type="number" class="form-control" name="isbn" id="isbn" value={{$book->isbn}} placeholder="Isbn Number">
                <span class="text-danger">  @error('isbn')
                    {{$message}}
                    @enderror
                </span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Description</label><br>
                <textarea rows="4" cols="50" id="desc" name="description"  placeholder="Description">
                    {{$book->description}}
                </textarea>
            </div>

            <button type="submit" class="btn btn-primary" name="submit" id="submit">Submit</button>

        </form>
    </div>
@endsection

laravel_lms_/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                        <h1> {{$user->name}} is  successfull loging! </h1>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel_lms_/resources/views/showauthor.blade.php
@extends('layouts.app')

@section('content')

<table class="table table-striped table-hover table-dark">
    <thead>
    <tr>
        <th scope="col">FullName</th>
        <th scope="col">Dob</th>
        <th scope="col">Gender</th>
        <th scope="col">Address</th>
        <th scope="col">Mobile_no</th>
        <th scope="col">Description</th>
        <th scope="col">Status</th>
        <th scope="col">Created At</th>
        <th scope="col">Updated At</th>
        <th scope="col"><Activity></Activity></th>
    </tr>
    </thead>
        <tbody>
            <tr>
              <th scope="row">{{$author->fullname}}</th>
                <td>{{$author->dob}}</td>
                <td>{{$author->gender}}</td>
                <td>{{$author->address_ }}</td>
                <td>{{$author->mobile_no}}</td>
                <td>{{$author->description_}}</td>
                <td>{{$author->status}}</td>
                <td>{{$author->created_at}}</td>
                <td>{{$author->updated_at}}</td>
            </tr>

        </tbody>
</table>
@endsection

laravel_lms_/resources/views/showbook.blade.php
@extends('layouts.app')

@section('content')

    <table class="table table-striped table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">Author_id</th>
            <th scope="col">Title</th>
            <th scope="col">pages</th>
            <th scope="col">langauge</th>
            <th scope="col">cover_image</th>
            <th scope="col">isbn</th>
            <th scope="col">description</th>
            <th scope="col">status</th>
            <th scope="col">Created At</th>
            <th scope="col">Updated At</th>
            <th scope="col"><Activity></Activity></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{$book->author_id}}</th>
            <td>{{$book->title}}</td>
            <td>{{$book->pages}}</td>
            <td>{{$book->langauge }}</td>
            <td><img src="{{$book->cover_image  }}" height="100px" width="100px"></td>
            <td>{{$book->isbn}}</td>
            <td>{{$book->description}}</td>
            <td>{{$book->created_at}}</td>
            <td>{{$book->updated_at}}</td>
        </tr>

        </tbody>
    </table>
@endsection